[main]
domain = 'yourdomain.com'
ns1 = '127.0.0.1'
ns2 = '0.0.0.0'

# Server address
listen_addr = '0.0.0.0:53'

# Debug (0 or 1)
debug = 0

# Default TTL
ttl = 60

# Use compression by default (0 or 1)
compression = 1

# Parse the EDNS(0) and its OPT pseudo-record (0 or 1)
parse_edns0 = 1

# Default latency (in ms)
sleep = 0

# A 3rdparty domain which we don't own
a3rdparty_domain = 'a3rdparty.net'

# When enabled, PolarDNS will respond authoritatively (AA=1) for *any* domain.
# WARNING: This breaks DNS protocol compliance and can mislead resolvers.
# Use only in isolated test environments. DO NOT expose to the public internet.
authoritative_for_any = 0

known_servers = """
127.0.0.1   localhost
1.2.3.4     powerdns1
1.2.3.5     powerdns2
2.3.4.5     bind-test1
4.5.6.7     msdns-test1
"""

# Delegated subdomains along with the list of nameservers to which they are delegated.
# Example: <subdomain>  <good glue>  <bad glue>
delegated_subdomains = """
sub.yourdomain.com                    127.0.1.1   127.0.1.2
some.other.subdomain.yourdomain.com   127.0.2.1   127.0.2.2
"""
