[module]
name = "htchain"
type = "feature"
info = "HTTPS Alias Chains"
short = "HTTPS chain alias generator"
category = "Alias chains"
records = "HTTPS"
tags = "Domain Lock-Up, Denial of Service"
rfc = "RFC9460"
desc = '''
This module implements **incremental alias chains** using **HTTPS (HyperText Transfer Protocol Secure)** records. It returns an alias record with an incremented domain name index, forming a chain that continues to increment indefinitely.

Specifically, this module generates a HTTPS alias record in the format `htchain###.yourdomain.com`, where `###` represents the incremented index.

The concept is that if the client/resolver attempts to resolve this alias further, it will generate yet another incremented alias, causing the process to continue indefinitely and potentially keeping the resolver occupied.

However, in practice, most modern resolvers detect such chains and terminate the resolution after encountering a certain number of consecutive aliases (e.g., 20 aliases) or upon reaching a specified time limit for the resolution (e.g., 30 seconds).

Note that this feature provides the same functionality as requesting a HTTPS record for the generic [chain] feature.

:warning:**BEWARE**:warning:This could potentially lead to a **domain lock-up (DoS)**.
'''
format = '''
**`htchain<NUMBER>.yourdomain.com`**

Where:

- The **`<NUMBER>`** parameter specifies an arbitrary number that will be incremented in the response.
'''
seealso = "htalias, htloop, chain, cnchain, dnchain, htchain, mxchain, nschain, spfchain, srchain, svchain"

[[module.example]]
description = "By default, the module generates an HTTPS alias record with the index of 1:"
command = "dig htchain.yourdomain.com @127.0.0.1"

[[module.example]]
description = "If we attempt to resolve the resulting domain name (`htchain1.yourdomain.com`), we receive an incremented alias record:"
command = "dig htchain1.yourdomain.com @127.0.0.1"

[[module.example]]
description = "If we continue to resolve the next domain name (`htchain2.yourdomain.com`), we again receive an incremented alias record:"
command = "dig htchain2.yourdomain.com @127.0.0.1"

[[module.example]]
description = "This resolution process can continue indefinitely, as there are no limits on the size of the index number. Each resolution yields another incremented alias record:"
command = "dig htchain9999999999999999999999999.yourdomain.com @127.0.0.1"
append = "The domain name will never be fully resolved as the incremental process continues indefinitely."

[module.code]
python = '''
           elif req.first_subdomain.startswith("htchain"):
              # Send incremented HTTPS alias (RFC 9460).
              new_domain_name = increment_chain()
              ### DNS header ########
              buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
              ### QUESTION SECTION ########
              if resp.noq: buffer += convDom2Bin(req.full_domain_20) + req.type_bin + req.class_bin
              ### ANSWER SECTION ########
              # HTTPS alias record
              bindom = convDom2Bin(new_domain_name)
              data_len = 2+len(bindom)  # SvcPriority (2 bytes) + the target name
              buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain_20)
              buffer += getTypeBin("HTTPS") + getClassBin("IN")
              buffer += struct.pack(">L", resp.TTL)    ## TTL
              buffer += struct.pack(">H", data_len)    ## Data length
              buffer += struct.pack(">H", 0)           ## SvcPriority (0 means alias mode - RFC 9460)
              buffer += bindom                         ## TargetName
              # log and send
              log("HTTPS %s" % (new_domain_name))
              send_buf(self, buffer)
              #####################################################################
'''
