[module]
name = "spfloop"
type = "feature"
info = "SPF (TXT) Alias Loops"
short = "SPF (TXT) loop alias generator"
category = "Alias loops"
records = "TXT, SPF"
tags = "Domain Lock-Up, Denial of Service"
rfc = "RFC4408, RFC7208"
desc = '''
This module implements **alias loops** using **SPF (Sender Policy Framework)** records. The loops can be a **direct loop**, where the alias points back to the **same domain name** as in the original query, or they can include **multiple elements**, cycling through a specified number of domains.

The idea is that if the client/resolver decides to resolve this further, it will enter an **infinite loop**. In practice, however, most modern resolvers detect such loops and terminate the resolution.

The SPF protocol is used to specify which mail servers are authorized to send emails on behalf of a domain, and SPF records are typically published within TXT records in DNS.

Note that this feature provides the same functionality as requesting a TXT record for the generic [loop] feature.

:warning:**BEWARE**:warning:This can potentially lead to a domain lock-up (DoS).
'''
format = '''
**`spfloop.<NUMBER>.yourdomain.com`**

Where:

- The **`<NUMBER>`** parameter specifies the number of elements the loop should contain.
'''
seealso = "spfalias1, spfalias2, spfchain, cnloop, dnloop, htloop, loop, mxloop, nptenumloop, nsloop, ptrloop1, ptrloop2, spfloop, srloop, svloop"

[[module.example]]
description = "In this example, we see a direct loop formed by sending a query that results in a SPF record containing the exact same domain name as the one in the query:"
command = "dig spfloop.yourdomain.com @127.0.0.1"

[[module.example]]
description = "In this example, we request a SPF alias loop consisting of 5 elements:"
command = "dig spfloop.5.yourdomain.com @127.0.0.1"
append = "The resulting domain name `spfloop.5.1.yourdomain.com` represents the 1st element of the loop."

[[module.example]]
description = "By resolving the 1st element, we are pointed to the 2nd element of the loop:"
command = "dig spfloop.5.1.yourdomain.com @127.0.0.1"
append = "This continues up to the 5th and final element - `spfloop.5.5.yourdomain.com`."

[[module.example]]
description = "By resolving the final element of the loop, we are directed back to the 1st element again:"
command = "dig spfloop.5.5.yourdomain.com @127.0.0.1"
append = "We can see that we are indeed pointed back to the 1st element again, forming a loop."

[module.code]
python = '''
if req.first_subdomain.startswith("spfloop"):
   # Do a SPF(TXT) loop
   if req.subdomains[1].isnumeric() and req.subdomains[2].isnumeric():
      # we are already in a loop, e.g.:
      # spfloop.10.4.yourdomain.com
      max = int(req.subdomains[1])
      cur = int(req.subdomains[2])
      if cur >= max:
         # go back to the beginning of the loop
         new_domain_name = req.subdomains_20[0] + "." + str(max) + ".1"
      else:
         # increment the current index
         new_domain_name = req.subdomains_20[0] + "." + str(max) + "." + str(cur+1)
      for i in range(len(req.subdomains)-3):
         new_domain_name += "." + req.subdomains_20[i+3]
   elif req.subdomains[1].isnumeric():
      # we are in beginning of a loop with a requested max value, e.g.:
      # spfloop.10.yourdomain.com
      max = int(req.subdomains[1])
      if max < 1:
         max = 1
      new_domain_name = req.subdomains_20[0] + "." + str(max) + "." + "1"
      for i in range(len(req.subdomains)-2):
         new_domain_name += "." + req.subdomains_20[i+2]
   else:
      # just immediate loop
      new_domain_name = req.full_domain_20
   ### DNS header ########
   buffer = prep_dns_header(b'\x84\x00', req.QURR, 1, 0, 0)
   ### QUESTION SECTION ########
   if resp.noq: buffer += convDom2Bin(req.full_domain_20) + req.type_bin + req.class_bin
   ### ANSWER SECTION ########
   # TXT SPF
   buffer += b'\xc0\x0c' if resp.compress else convDom2Bin(req.full_domain_20)
   data = "v=spf1 include:" + new_domain_name + " ~all"
   buffer += getTypeBin("TXT") + getClassBin("IN")
   buffer += struct.pack(">L", resp.TTL)         ## TTL
   buffer += struct.pack(">H", len(data)+1)      ## Data length (2B)
   buffer += struct.pack(">B", len(data))        ## TXT length (1B)
   buffer += data.encode("utf-8")                ## TXT SPF value
   # log and send
   log("SPF(TXT) LOOP %s" % (new_domain_name))
   send_buf(self, buffer)
   #####################################################################
'''
